version: "3"
services:
  hackiathon-db:
    image: postgres:17.0
    ports:
      - "4002:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      # - ${DOCKER_DATA}/postgres-data:/var/lib/postgresql/data
      - ./backend/src/databases/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: hackiathon-db

    restart: unless-stopped
